language: php
php:
- 5.5.9
- 5.5
- 5.6
- 7.0
- 7.1
- hhvm
env:
  global:
    - setup=basic
matrix:
  allow_failures:
    - php: 7.1
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable
install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
script: ./vendor/bin/phpunit  --coverage-clover ./tests/logs/clover.xml
after_script:
- php vendor/bin/coveralls -v
cache:
  directories:
    - $HOME/.composer/cache
