language: php
php:
- 5.5.9
- 5.5
- 5.6
- 7.0
- hhvm
before_script:
- composer install --prefer-dist --no-interaction
script: ./vendor/bin/phpunit  --coverage-clover ./tests/logs/clover.xml
after_script:
- php vendor/bin/coveralls -v
cache:
  directories:
    - $HOME/.composer/cache
